### ISSUE TITLE
Incorrect class selection when class def has no parenthesis

### ISSUE THREAD

**Issue by Kazy** [jeetsukumaran/vim-pythonsense#5] opened 2018-08-15 10:52 UTC
If you define a class like that:
```python
class Foo:
    bar = "bar"
    baz = "baz"

def unrelated_function():
    pass
```
two bugs happen:
- With `ic`, the content of the next function will be selected instead. If you have a method definition in the `Foo` class, the body of that function will be selected.
- With `ac`, the whole class + the next function are selected.

The text objects behave correctly when the class definition has parenthesis (`class Foo():`).

**Comment by vijjo** [comment] 2019-11-06 09:15
I can confirm the issue. In python 3, classes may not have parentheses and the plugin doesn't properly recognize the `class` object. For example, in

```python
class Email:

    def __init__(self):
        self.is_sent = False

    def send_email(self):
        self.is_sent = True
```

`vic` will select the following visual part:

```python
        self.is_sent = False

    def send_email(self):
        self.is_sent = True
```

**Comment by jeetsukumaran** [comment] 2019-11-07 01:14
Happy to accept a PR for this. Otherwise it is going to have wait till I have time to look into it myself.

**Comment by jeetsukumaran** [comment] 2019-11-07 17:12
This should be fixed thanks to @Kazy https://github.com/jeetsukumaran/vim-pythonsense/pull/4/commits/6283f506049a060cc47b5960a1edf9a497235929

**Closed as completed by jeetsukumaran** 2019-11-07 17:12 UTC

**Comment by vijjo** [comment] 2019-11-08 00:13
Awesome! Thank @Kazy

**Comment by vijjo** [comment] 2019-11-08 00:34
Another issue has arisen. With @Kazy's fix, I can no longer map my own keys. For example, I would like to remap the class object because I already reserved `ac` and `ic` for comments:
```vim
omap <buffer> ak <Plug>(PythonsenseOuterClassTextObject)
omap <buffer> ik <Plug>(PythonsenseInnerClassTextObject)
```

**Comment by Kazy** [comment] 2019-11-08 08:05
@hieuvijjo I couldn't replicate your issue. Executing your mappings works correctly, both in a buffer or directly in my vimrc without the `<buffer>` part. 

I did find an already existing bug though in the check to see if a mapping already exists to a function. The mappings were always set. I'll send a PR (see #10), let me know if that was actually your issue or not. I otherwise can't see how my PR could have broken this.

**Comment by vijjo** [comment] 2019-11-08 08:48
I realize that if I set `omap`, the mapping doesn't work. It works with simple `map`. 
However, with `map`, there would be some delay switching from `normal mode` to `insert mode` as vim waits for the next key after `i` or `a`.

**Comment by vijjo** [comment] 2019-11-08 09:17
Ah, if I map both `omap` and `xmap`, everything works fine. Perhaps, we should update the document/readme to notice people about the potential delay with `map`. (Or the delay only happens with my vim?)
Here is my mapping that works:
```vim
let g:is_pythonsense_suppress_object_keymaps = 1
augroup pythonsense_objects
    autocmd!
    autocmd FileType python omap <buffer> ak <Plug>(PythonsenseOuterClassTextObject)
    autocmd FileType python xmap <buffer> ak <Plug>(PythonsenseOuterClassTextObject)
    autocmd FileType python omap <buffer> ik <Plug>(PythonsenseInnerClassTextObject)
    autocmd FileType python xmap <buffer> ik <Plug>(PythonsenseInnerClassTextObject)
    autocmd FileType python omap <buffer> af <Plug>(PythonsenseOuterFunctionTextObject)
    autocmd FileType python xmap <buffer> af <Plug>(PythonsenseOuterFunctionTextObject)
    autocmd FileType python omap <buffer> if <Plug>(PythonsenseInnerFunctionTextObject)
    autocmd FileType python xmap <buffer> if <Plug>(PythonsenseInnerFunctionTextObject)
    autocmd FileType python omap <buffer> ad <Plug>(PythonsenseOuterDocStringTextObject)
    autocmd FileType python xmap <buffer> ad <Plug>(PythonsenseOuterDocStringTextObject)
    autocmd FileType python omap <buffer> id <Plug>(PythonsenseInnerDocStringTextObject)
    autocmd FileType python xmap <buffer> id <Plug>(PythonsenseInnerDocStringTextObject)
augroup END
```

**Comment by Kazy** [comment] 2019-11-08 09:28
Indeed the `README` should be updated to not use `map` but `omap` and `vmap`, like in the actual code. The mappings don't make sense in normal mode.
